# Generated by Django 4.1.7 on 2023-03-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_verify', models.FileField(upload_to='uploads/')),
                ('pdf_sign', models.FileField(upload_to='uploads/')),
                ('certificado', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
